name: CITasks

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: "25"
        distribution: "temurin"
        cache: gradle

    - name: Upload Subproject Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: subproject-jars
        path: |
          core/build/libs/*.jar
          joml/build/libs/*.jar
