name: CITasks

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: "25"
        distribution: "temurin"
        cache: gradle

    - name: Prepare Release
      run: ./gradlew publish
      env: 
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Upload Subproject Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: subproject-jars
        path: |
          core/build/libs/*.jar
          joml/build/libs/*.jar
